# https://taskfile.dev

version: '3'

vars:
  REGISTRY: 'apgmckay'
  DOCKER_RUN: 'docker run -p 8080:8080 bumpy:latest'
  LOCAL_RUN: './bumpy server'

tasks:
  build:
    desc: Builds go binary
    cmds:
      - echo "Building bumpy go..."
      - go build .
      - echo "To run server:"
      - echo "{{ .LOCAL_RUN }}"
  build_docker:
    desc: Builds docker image of bumpy
    cmds:
      - echo "Build bumpy docker image..."
      - docker build . -t bumpy:$(git rev-parse --short=6 HEAD) -t bumpy:latest -t {{ .REGISTRY }}/bumpy:latest 
      - echo "To run server:"
      - echo "{{ .DOCKER_RUN }}"
  push_docker:
    desc: Push docker image of bumpy
    cmds:
      - echo "Pushing bumpy docker image..."
      - docker push apgmckay/bumpy:latest
  cloc_project:
    desc: Count lines of code for the project
    cmds:
      - echo "Counting lines of code for project..."
      - find . -name "*.go" | xargs cloc --force-lang=Go
      - echo "Counting line of code done."
