# https://taskfile.dev

version: '3'

vars:
  DOCKER_RUN: 'docker run -p 8080:8080 bumpy:latest'
  LOCAL_RUN: './bumpy server'
  COMMIT_SHA:
    sh: git rev-parse --short=6 HEAD
tasks:
  build:
    desc: Builds go binary
    cmds:
      - echo "Building bumpy go..."
      - go build .
      - echo "To run server:"
      - echo "{{ .LOCAL_RUN }}"
  build_docker:
    desc: Builds docker image of bumpy
    cmds:
      - echo "Build bumpy docker image..."
      - docker build . -t bumpy:{{ .COMMIT_SHA }} -t apgmckay/bumpy:{{ .COMMIT_SHA }}
      - echo "To run server:"
      - echo "{{ .DOCKER_RUN }}"
  push_docker:
    desc: Push docker image of bumpy
    cmds:
      - echo "Push bumpmy docker images..."
      - docker push apgmckay/bumpy:{{ .COMMIT_SHA }}
      - echo "Pushing done."
  build_and_push_docker:
    desc: Build and Push docker image
    cmds:
      - task: build_docker
      - task: push_docker
  cloc_project:
    desc: Count lines of code for the project
    cmds:
      - echo "Counting lines of code for project..."
      - find . -name "*.go" | xargs cloc --force-lang=Go
      - echo "Counting line of code done."
  kafka_start:
    desc: Start Kafka
    cmds:
      - echo "Kafka install..."
      - docker run -p 9092:9092 -d apache/kafka:4.1.0
      - echo "Kafka installed."
  kafka_stop:
    desc: Killing Kafka
    cmds:
      - echo "Killing Kafka"
      - docker stop $(docker ps --filter "ancestor=apache/kafka:4.1.0" --format "{{.ID}}")
      - echo "Kafka killed."
  helm_install:
    desc: Install helm chart
    cmds:
      - echo "Helm install..."
      - helm install bumpy ./helm/
      - echo "Installed."
