# https://taskfile.dev

version: '3'

vars:
  GREETING: Hello, World!

tasks:
  build:
    desc: Builds go binary
    cmds:
      - echo "Building bumpy go..."
      - go build .
  build_docker:
    desc: Builds docker image of bumpy
    cmds:
      - echo "Build bumpy docker image..."
      - docker build .
  cloc_project:
    desc: Count lines of code for the project
    cmds:
      - echo "Counting lines of code for project..."
      - find . -name "*.go" | xargs cloc --force-lang=Go
      - echo "Counting line of code done."
