apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: bumpy-hpa
  labels:
    app: bumpy
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: bumpy-deployment
  minReplicas: {{ .Values.autoscaling.minReplicas | default 1 }}
  maxReplicas: {{ .Values.autoscaling.maxReplicas | default 10 }}
  metrics:
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: {{ .Values.autoscaling.targetMemoryUtilizationPercentage | default 80 }}
